### ISSUE TITLE
remove unnecessary files from ``data/``

### ISSUE THREAD

**Issue by tseppelt** [marioangst/integrateR#18]
Currently, the following files are stored in ``data/``:
```
actor_concept_el.csv
actor_el.csv
actors.csv
cld_concepts.csv
cld_el.csv
dummy_net.RData
ml_adj_mat.csv
reussebene_mlnet.RData
sesType.csv
```
The R package mechanisms make all these objects available in the package environment. I think for most of the files this is not necessary. Furthermore these files cause warnings when building the package. The files which are not necessary should be moved somewhere else. See http://r-pkgs.had.co.nz/data.html

**Comment by marioangst** [comment]
addressed in 08fcefee8abd52d5d72fbd9319243cc42f461655
